# docker-compose.yaml
version: "3.1"
services:
  svr:
    build: ./svr
    ports:
    - 50051:50051
    environment:
      MICROADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
  cgi:
    build: ./cgi
    ports:
    - 1234:1234
    environment:
      MICROADDRESS: ":1234"
      MICRO_REGISTRY: "mdns"
